services:

  web:
    build: ./project
    env_file: ./project/.env
    entrypoint: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    env_file: ./project/.env
